# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(730, 560)
        MainWindow.setMinimumSize(QtCore.QSize(730, 560))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        MainWindow.setFont(font)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setStyleSheet("QMainWindow {background: transparent; }\n"
"QToolTip {\n"
"    color: #ffffff;\n"
"    background-color: rgba(27, 29, 35, 160);\n"
"    border: 1px solid rgb(40, 40, 40);\n"
"    border-radius: 2px;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background: transparent;\n"
"color: rgb(210, 210, 210);")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_11.setContentsMargins(10, 10, 10, 10)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.frame_main = QtWidgets.QFrame(self.centralwidget)
        self.frame_main.setStyleSheet("/* LINE EDIT */\n"
"QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"/* SCROLL BARS */\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 14px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(85, 170, 255);\n"
"    min-width: 25px;\n"
"    border-radius: 7px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-bottom-left-radius: 7px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"/* CHECKBOX */\n"
"QCheckBox::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QCheckBox::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QCheckBox::indicator:checked {\n"
"    background: 3px solid rgb(52, 59, 72);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"    background-image: url(icons/16x16/cil-check-alt.png);\n"
"}\n"
"\n"
"/* RADIO BUTTON */\n"
"QRadioButton::indicator {\n"
"    border: 3px solid rgb(52, 59, 72);\n"
"    width: 15px;\n"
"    height: 15px;\n"
"    border-radius: 10px;\n"
"    background: rgb(44, 49, 60);\n"
"}\n"
"QRadioButton::indicator:hover {\n"
"    border: 3px solid rgb(58, 66, 81);\n"
"}\n"
"QRadioButton::indicator:checked {\n"
"    background: 3px solid rgb(94, 106, 130);\n"
"    border: 3px solid rgb(52, 59, 72);    \n"
"}\n"
"\n"
"/* SLIDERS */\n"
"QSlider::groove:horizontal {\n"
"    border-radius: 9px;\n"
"    height: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:horizontal:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:horizontal {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:horizontal:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:horizontal:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"QSlider::groove:vertical {\n"
"    border-radius: 9px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QSlider::groove:vertical:hover {\n"
"    background-color: rgb(55, 62, 76);\n"
"}\n"
"QSlider::handle:vertical {\n"
"    background-color: rgb(85, 170, 255);\n"
"    border: none;\n"
"    height: 18px;\n"
"    width: 18px;\n"
"    margin: 0px;\n"
"    border-radius: 9px;\n"
"}\n"
"QSlider::handle:vertical:hover {\n"
"    background-color: rgb(105, 180, 255);\n"
"}\n"
"QSlider::handle:vertical:pressed {\n"
"    background-color: rgb(65, 130, 195);\n"
"}\n"
"\n"
"")
        self.frame_main.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_top = QtWidgets.QFrame(self.frame_main)
        self.frame_top.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_top.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_top.setStyleSheet("background-color: transparent;")
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_toggle = QtWidgets.QFrame(self.frame_top)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_toggle.setStyleSheet("background-color: rgb(27, 29, 35);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btn_toggle_menu = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_toggle_menu.sizePolicy().hasHeightForWidth())
        self.btn_toggle_menu.setSizePolicy(sizePolicy)
        self.btn_toggle_menu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_toggle_menu.setStyleSheet("QPushButton {\n"
"\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"    border: none;\n"
"    background-color: rgb(27, 29, 35);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_toggle_menu.setText("")
        self.btn_toggle_menu.setIconSize(QtCore.QSize(24, 24))
        self.btn_toggle_menu.setObjectName("btn_toggle_menu")
        self.verticalLayout_3.addWidget(self.btn_toggle_menu)
        self.horizontalLayout_16.addWidget(self.frame_toggle)
        self.frame_top_right = QtWidgets.QFrame(self.frame_top)
        self.frame_top_right.setStyleSheet("background: transparent;")
        self.frame_top_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_right.setObjectName("frame_top_right")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_right)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_top_btns = QtWidgets.QFrame(self.frame_top_right)
        self.frame_top_btns.setMaximumSize(QtCore.QSize(16777215, 42))
        self.frame_top_btns.setStyleSheet("background-color: rgba(27, 29, 35, 200)")
        self.frame_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_btns.setObjectName("frame_top_btns")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_top_btns)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_label_top_btns = QtWidgets.QFrame(self.frame_top_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_label_top_btns.sizePolicy().hasHeightForWidth())
        self.frame_label_top_btns.setSizePolicy(sizePolicy)
        self.frame_label_top_btns.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_top_btns.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_top_btns.setObjectName("frame_label_top_btns")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_label_top_btns)
        self.horizontalLayout_13.setContentsMargins(5, 0, 10, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_icon_top_bar = QtWidgets.QFrame(self.frame_label_top_btns)
        self.frame_icon_top_bar.setMaximumSize(QtCore.QSize(30, 30))
        self.frame_icon_top_bar.setStyleSheet("background: transparent;\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"image: url(icons/16x16/cil-terminal.png);\n"
"")
        self.frame_icon_top_bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_icon_top_bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_icon_top_bar.setLineWidth(0)
        self.frame_icon_top_bar.setObjectName("frame_icon_top_bar")
        self.horizontalLayout_13.addWidget(self.frame_icon_top_bar)
        self.label_title_bar_top = QtWidgets.QPushButton(self.frame_label_top_btns)
        self.label_title_bar_top.setMinimumSize(QtCore.QSize(0, 0))
        self.label_title_bar_top.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_title_bar_top.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.label_title_bar_top.setStyleSheet("background: transparent;\n"
"border: 0;\n"
"text-align: left;\n"
"\n"
"")
        self.label_title_bar_top.setObjectName("label_title_bar_top")
        self.horizontalLayout_13.addWidget(self.label_title_bar_top)
        self.frame_13 = QtWidgets.QFrame(self.frame_label_top_btns)
        self.frame_13.setStyleSheet("background: transparent;\n"
"")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_13.addWidget(self.frame_13)
        self.horizontalLayout_12.addWidget(self.frame_label_top_btns)
        self.frame_btns_right = QtWidgets.QFrame(self.frame_top_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_btns_right.sizePolicy().hasHeightForWidth())
        self.frame_btns_right.setSizePolicy(sizePolicy)
        self.frame_btns_right.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_btns_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_btns_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_btns_right.setObjectName("frame_btns_right")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_btns_right)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.btn_minimize = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_minimize.sizePolicy().hasHeightForWidth())
        self.btn_minimize.setSizePolicy(sizePolicy)
        self.btn_minimize.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_minimize.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_minimize.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"image: url(icons/16x16/cil-window-minimize.png);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_minimize.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icons/16x16/cil-window-minimize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_minimize.setIcon(icon)
        self.btn_minimize.setObjectName("btn_minimize")
        self.horizontalLayout_14.addWidget(self.btn_minimize)
        self.btn_maximize_restore = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_maximize_restore.sizePolicy().hasHeightForWidth())
        self.btn_maximize_restore.setSizePolicy(sizePolicy)
        self.btn_maximize_restore.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_maximize_restore.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_maximize_restore.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"    background-color: transparent;\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"image: url(icons/16x16/cil-window-maximize.png);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_maximize_restore.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("icons/16x16/cil-window-maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_maximize_restore.setIcon(icon1)
        self.btn_maximize_restore.setObjectName("btn_maximize_restore")
        self.horizontalLayout_14.addWidget(self.btn_maximize_restore)
        self.btn_close = QtWidgets.QPushButton(self.frame_btns_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_close.sizePolicy().hasHeightForWidth())
        self.btn_close.setSizePolicy(sizePolicy)
        self.btn_close.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_close.setMaximumSize(QtCore.QSize(40, 16777215))
        self.btn_close.setStyleSheet("QPushButton {    \n"
"    border: none;\n"
"background: transparent;\n"
"background-position: center;\n"
"background-repeat: no-repeat;\n"
"image: url(icons/16x16/cil-x.png);\n"
"\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.btn_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("icons/16x16/cil-x.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_close.setIcon(icon2)
        self.btn_close.setObjectName("btn_close")
        self.horizontalLayout_14.addWidget(self.btn_close)
        self.horizontalLayout_12.addWidget(self.frame_btns_right, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_4.addWidget(self.frame_top_btns)
        self.frame_top_info = QtWidgets.QFrame(self.frame_top_right)
        self.frame_top_info.setMaximumSize(QtCore.QSize(16777215, 65))
        self.frame_top_info.setStyleSheet("background-color: rgb(39, 44, 54);")
        self.frame_top_info.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_info.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_info.setObjectName("frame_top_info")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_top_info)
        self.horizontalLayout_15.setContentsMargins(10, 0, 10, 0)
        self.horizontalLayout_15.setSpacing(0)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_top_info_1 = QtWidgets.QLabel(self.frame_top_info)
        self.label_top_info_1.setMaximumSize(QtCore.QSize(16777215, 15))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_top_info_1.setFont(font)
        self.label_top_info_1.setStyleSheet("color: rgb(98, 103, 111); ")
        self.label_top_info_1.setText("")
        self.label_top_info_1.setObjectName("label_top_info_1")
        self.horizontalLayout_15.addWidget(self.label_top_info_1)
        self.label_top_info_2 = QtWidgets.QLabel(self.frame_top_info)
        self.label_top_info_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_top_info_2.setMaximumSize(QtCore.QSize(250, 20))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setBold(True)
        font.setWeight(75)
        self.label_top_info_2.setFont(font)
        self.label_top_info_2.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_top_info_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_top_info_2.setObjectName("label_top_info_2")
        self.horizontalLayout_15.addWidget(self.label_top_info_2)
        self.verticalLayout_4.addWidget(self.frame_top_info)
        self.horizontalLayout_16.addWidget(self.frame_top_right)
        self.verticalLayout_2.addWidget(self.frame_top)
        self.frame_center = QtWidgets.QFrame(self.frame_main)
        self.frame_center.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_center.setObjectName("frame_center")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_center)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.frame_left_menu = QtWidgets.QFrame(self.frame_center)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_left_menu.sizePolicy().hasHeightForWidth())
        self.frame_left_menu.setSizePolicy(sizePolicy)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(70, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_left_menu.setStyleSheet("background-color: rgb(27, 29, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_12.setSpacing(1)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_menus.setObjectName("frame_menus")
        self.layout_menus = QtWidgets.QVBoxLayout(self.frame_menus)
        self.layout_menus.setContentsMargins(0, 0, 0, 0)
        self.layout_menus.setSpacing(0)
        self.layout_menus.setObjectName("layout_menus")
        self.verticalLayout_12.addWidget(self.frame_menus, 0, QtCore.Qt.AlignTop)
        self.frame_extra_menus = QtWidgets.QFrame(self.frame_left_menu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_extra_menus.sizePolicy().hasHeightForWidth())
        self.frame_extra_menus.setSizePolicy(sizePolicy)
        self.frame_extra_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_extra_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_extra_menus.setObjectName("frame_extra_menus")
        self.layout_menu_bottom = QtWidgets.QVBoxLayout(self.frame_extra_menus)
        self.layout_menu_bottom.setContentsMargins(0, 0, 0, 25)
        self.layout_menu_bottom.setSpacing(10)
        self.layout_menu_bottom.setObjectName("layout_menu_bottom")
        self.label_user_icon = QtWidgets.QLabel(self.frame_extra_menus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_user_icon.sizePolicy().hasHeightForWidth())
        self.label_user_icon.setSizePolicy(sizePolicy)
        self.label_user_icon.setMinimumSize(QtCore.QSize(60, 60))
        self.label_user_icon.setMaximumSize(QtCore.QSize(60, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_user_icon.setFont(font)
        self.label_user_icon.setStyleSheet("QLabel {\n"
"    border-radius:5px;\n"
"    background-color: rgb(44, 49, 60);\n"
"    border: 5px solid rgb(39, 44, 54);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;\n"
"    image: url(icons/24x24/cil-user.png);\n"
"}")
        self.label_user_icon.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_user_icon.setText("")
        self.label_user_icon.setAlignment(QtCore.Qt.AlignCenter)
        self.label_user_icon.setObjectName("label_user_icon")
        self.layout_menu_bottom.addWidget(self.label_user_icon, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout_12.addWidget(self.frame_extra_menus, 0, QtCore.Qt.AlignBottom)
        self.horizontalLayout_24.addWidget(self.frame_left_menu)
        self.frame_content_right = QtWidgets.QFrame(self.frame_center)
        self.frame_content_right.setStyleSheet("background-color: rgb(44, 49, 60);")
        self.frame_content_right.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content_right.setObjectName("frame_content_right")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_content_right)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_content = QtWidgets.QFrame(self.frame_content_right)
        self.frame_content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content.setObjectName("frame_content")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_content)
        self.verticalLayout_9.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_content)
        self.stackedWidget.setStyleSheet("background: transparent;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.vkLoginPage = QtWidgets.QWidget()
        self.vkLoginPage.setObjectName("vkLoginPage")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.vkLoginPage)
        self.verticalLayout_10.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_10.setContentsMargins(-1, 9, -1, 20)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.vkImage = QtWidgets.QLabel(self.vkLoginPage)
        self.vkImage.setMinimumSize(QtCore.QSize(100, 100))
        self.vkImage.setMaximumSize(QtCore.QSize(100, 100))
        self.vkImage.setStyleSheet("QLabel {\n"
"    border-radius: 50px;\n"
"    background-color: rgb(44, 49, 60);\n"
"    border: 5px solid rgb(39, 44, 54);\n"
"    background-position: center;\n"
"    background-repeat: no-repeat;    \n"
"    \n"
"    image: url(icons/vk/vk.png);\n"
"\n"
"}")
        self.vkImage.setText("")
        self.vkImage.setAlignment(QtCore.Qt.AlignCenter)
        self.vkImage.setObjectName("vkImage")
        self.verticalLayout_10.addWidget(self.vkImage, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit = QtWidgets.QLineEdit(self.vkLoginPage)
        self.lineEdit.setMinimumSize(QtCore.QSize(300, 40))
        self.lineEdit.setMaximumSize(QtCore.QSize(300, 40))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_10.addWidget(self.lineEdit, 0, QtCore.Qt.AlignHCenter)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.vkLoginPage)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(300, 40))
        self.lineEdit_2.setMaximumSize(QtCore.QSize(300, 40))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_10.addWidget(self.lineEdit_2, 0, QtCore.Qt.AlignHCenter)
        self.checkBox = QtWidgets.QCheckBox(self.vkLoginPage)
        self.checkBox.setMinimumSize(QtCore.QSize(300, 0))
        self.checkBox.setMaximumSize(QtCore.QSize(300, 50))
        self.checkBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.checkBox.setChecked(True)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_10.addWidget(self.checkBox, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_4 = QtWidgets.QPushButton(self.vkLoginPage)
        self.pushButton_4.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_4.setMaximumSize(QtCore.QSize(100, 40))
        self.pushButton_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_4.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout_10.addWidget(self.pushButton_4, 0, QtCore.Qt.AlignHCenter)
        self.ResultOfLogin = QtWidgets.QLabel(self.vkLoginPage)
        self.ResultOfLogin.setMinimumSize(QtCore.QSize(300, 30))
        self.ResultOfLogin.setMaximumSize(QtCore.QSize(300, 50))
        self.ResultOfLogin.setStyleSheet("")
        self.ResultOfLogin.setAlignment(QtCore.Qt.AlignCenter)
        self.ResultOfLogin.setObjectName("ResultOfLogin")
        self.verticalLayout_10.addWidget(self.ResultOfLogin, 0, QtCore.Qt.AlignHCenter)
        self.stackedWidget.addWidget(self.vkLoginPage)
        self.LogsPage = QtWidgets.QWidget()
        self.LogsPage.setObjectName("LogsPage")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.LogsPage)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_14 = QtWidgets.QFrame(self.LogsPage)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_14)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.frame_14)
        self.plainTextEdit.setStyleSheet("QPlainTextEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"}\n"
"QPlainTextEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.plainTextEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.horizontalLayout_4.addWidget(self.plainTextEdit)
        self.verticalLayout_16.addWidget(self.frame_14)
        self.stackedWidget.addWidget(self.LogsPage)
        self.LikesPage = QtWidgets.QWidget()
        self.LikesPage.setObjectName("LikesPage")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.LikesPage)
        self.verticalLayout_14.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_14.setContentsMargins(0, 40, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_5 = QtWidgets.QFrame(self.LikesPage)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_5.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_5.setStyleSheet("")
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout.setContentsMargins(-1, 9, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_6 = QtWidgets.QFrame(self.frame_5)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(10, 10, 10, 10)
        self.gridLayout.setSpacing(10)
        self.gridLayout.setObjectName("gridLayout")
        self.SaveUrlButton = QtWidgets.QPushButton(self.frame_6)
        self.SaveUrlButton.setMinimumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.SaveUrlButton.setFont(font)
        self.SaveUrlButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SaveUrlButton.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("icons/16x16/cil-save.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SaveUrlButton.setIcon(icon3)
        self.SaveUrlButton.setCheckable(False)
        self.SaveUrlButton.setObjectName("SaveUrlButton")
        self.gridLayout.addWidget(self.SaveUrlButton, 0, 1, 1, 1)
        self.LabelLikesUrl = QtWidgets.QLineEdit(self.frame_6)
        self.LabelLikesUrl.setMinimumSize(QtCore.QSize(0, 40))
        self.LabelLikesUrl.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.LabelLikesUrl.setObjectName("LabelLikesUrl")
        self.gridLayout.addWidget(self.LabelLikesUrl, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.ResultSaveUrl = QtWidgets.QLabel(self.frame_6)
        self.ResultSaveUrl.setMinimumSize(QtCore.QSize(0, 30))
        self.ResultSaveUrl.setMaximumSize(QtCore.QSize(16777215, 50))
        self.ResultSaveUrl.setStyleSheet("border-radius: 2px;\n"
"padding: 10px;\n"
"")
        self.ResultSaveUrl.setText("")
        self.ResultSaveUrl.setObjectName("ResultSaveUrl")
        self.gridLayout.addWidget(self.ResultSaveUrl, 1, 1, 1, 1)
        self.LikestCheckBox = QtWidgets.QCheckBox(self.frame_6)
        self.LikestCheckBox.setMinimumSize(QtCore.QSize(100, 0))
        self.LikestCheckBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.LikestCheckBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LikestCheckBox.setChecked(True)
        self.LikestCheckBox.setObjectName("LikestCheckBox")
        self.gridLayout.addWidget(self.LikestCheckBox, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        self.gridLayout.setColumnStretch(0, 4)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(0, 2)
        self.verticalLayout_17.addLayout(self.gridLayout)
        self.verticalLayout.addWidget(self.frame_6)
        self.verticalLayout_14.addWidget(self.frame_5)
        self.frame_4 = QtWidgets.QFrame(self.LikesPage)
        self.frame_4.setEnabled(True)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_18.setContentsMargins(10, 0, 11, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.LikesCount = QtWidgets.QLineEdit(self.frame_7)
        self.LikesCount.setEnabled(True)
        self.LikesCount.setMinimumSize(QtCore.QSize(105, 39))
        self.LikesCount.setMaximumSize(QtCore.QSize(105, 16777215))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        self.LikesCount.setFont(font)
        self.LikesCount.setToolTipDuration(-1)
        self.LikesCount.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.LikesCount.setText("")
        self.LikesCount.setCursorPosition(0)
        self.LikesCount.setAlignment(QtCore.Qt.AlignCenter)
        self.LikesCount.setObjectName("LikesCount")
        self.horizontalLayout.addWidget(self.LikesCount)
        self.StartLikes = QtWidgets.QPushButton(self.frame_7)
        self.StartLikes.setMinimumSize(QtCore.QSize(105, 40))
        self.StartLikes.setMaximumSize(QtCore.QSize(105, 16777215))
        self.StartLikes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StartLikes.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.StartLikes.setObjectName("StartLikes")
        self.horizontalLayout.addWidget(self.StartLikes)
        self.StopLikes = QtWidgets.QPushButton(self.frame_7)
        self.StopLikes.setMinimumSize(QtCore.QSize(105, 40))
        self.StopLikes.setMaximumSize(QtCore.QSize(105, 16777215))
        self.StopLikes.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StopLikes.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.StopLikes.setObjectName("StopLikes")
        self.horizontalLayout.addWidget(self.StopLikes)
        self.ResultStartLikes = QtWidgets.QLabel(self.frame_7)
        self.ResultStartLikes.setMinimumSize(QtCore.QSize(140, 40))
        self.ResultStartLikes.setMaximumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ResultStartLikes.setFont(font)
        self.ResultStartLikes.setStyleSheet("QLabel {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"}")
        self.ResultStartLikes.setLineWidth(1)
        self.ResultStartLikes.setMidLineWidth(0)
        self.ResultStartLikes.setText("")
        self.ResultStartLikes.setScaledContents(False)
        self.ResultStartLikes.setAlignment(QtCore.Qt.AlignCenter)
        self.ResultStartLikes.setIndent(0)
        self.ResultStartLikes.setObjectName("ResultStartLikes")
        self.horizontalLayout.addWidget(self.ResultStartLikes, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 1)
        self.horizontalLayout.setStretch(3, 1)
        self.verticalLayout_18.addWidget(self.frame_7)
        self.verticalLayout_14.addWidget(self.frame_4)
        self.frame_16 = QtWidgets.QFrame(self.LikesPage)
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 16777208))
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_6.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_14.addWidget(self.frame_16, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.verticalLayout_14.setStretch(2, 1)
        self.stackedWidget.addWidget(self.LikesPage)
        self.RepostPage = QtWidgets.QWidget()
        self.RepostPage.setObjectName("RepostPage")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.RepostPage)
        self.verticalLayout_22.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_22.setContentsMargins(0, 40, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.frame_8 = QtWidgets.QFrame(self.RepostPage)
        self.frame_8.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_8.setStyleSheet("")
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_13.setContentsMargins(-1, 9, -1, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_4.setSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.SaveUrlButton_R = QtWidgets.QPushButton(self.frame_10)
        self.SaveUrlButton_R.setMinimumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.SaveUrlButton_R.setFont(font)
        self.SaveUrlButton_R.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SaveUrlButton_R.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.SaveUrlButton_R.setIcon(icon3)
        self.SaveUrlButton_R.setCheckable(False)
        self.SaveUrlButton_R.setObjectName("SaveUrlButton_R")
        self.gridLayout_4.addWidget(self.SaveUrlButton_R, 0, 1, 1, 1)
        self.LabelRepostsUrl = QtWidgets.QLineEdit(self.frame_10)
        self.LabelRepostsUrl.setMinimumSize(QtCore.QSize(0, 40))
        self.LabelRepostsUrl.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.LabelRepostsUrl.setObjectName("LabelRepostsUrl")
        self.gridLayout_4.addWidget(self.LabelRepostsUrl, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.ResultSaveUrl_R = QtWidgets.QLabel(self.frame_10)
        self.ResultSaveUrl_R.setMinimumSize(QtCore.QSize(0, 30))
        self.ResultSaveUrl_R.setMaximumSize(QtCore.QSize(16777215, 50))
        self.ResultSaveUrl_R.setStyleSheet("border-radius: 2px;\n"
"padding: 10px;\n"
"")
        self.ResultSaveUrl_R.setText("")
        self.ResultSaveUrl_R.setObjectName("ResultSaveUrl_R")
        self.gridLayout_4.addWidget(self.ResultSaveUrl_R, 1, 1, 1, 1)
        self.RepostsCheckBox = QtWidgets.QCheckBox(self.frame_10)
        self.RepostsCheckBox.setMinimumSize(QtCore.QSize(100, 0))
        self.RepostsCheckBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.RepostsCheckBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.RepostsCheckBox.setChecked(True)
        self.RepostsCheckBox.setObjectName("RepostsCheckBox")
        self.gridLayout_4.addWidget(self.RepostsCheckBox, 1, 0, 1, 1, QtCore.Qt.AlignTop)
        self.gridLayout_4.setColumnStretch(0, 4)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.gridLayout_4.setRowStretch(0, 2)
        self.verticalLayout_20.addLayout(self.gridLayout_4)
        self.verticalLayout_13.addWidget(self.frame_10)
        self.verticalLayout_22.addWidget(self.frame_8, 0, QtCore.Qt.AlignTop)
        self.frame_11 = QtWidgets.QFrame(self.RepostPage)
        self.frame_11.setEnabled(True)
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_21.setContentsMargins(10, 0, 11, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_3.setSpacing(7)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.RepostsCount = QtWidgets.QLineEdit(self.frame_12)
        self.RepostsCount.setEnabled(True)
        self.RepostsCount.setMinimumSize(QtCore.QSize(105, 40))
        self.RepostsCount.setMaximumSize(QtCore.QSize(105, 16777215))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        self.RepostsCount.setFont(font)
        self.RepostsCount.setToolTipDuration(-1)
        self.RepostsCount.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.RepostsCount.setText("")
        self.RepostsCount.setCursorPosition(0)
        self.RepostsCount.setAlignment(QtCore.Qt.AlignCenter)
        self.RepostsCount.setObjectName("RepostsCount")
        self.horizontalLayout_3.addWidget(self.RepostsCount)
        self.Reward = QtWidgets.QLineEdit(self.frame_12)
        self.Reward.setMinimumSize(QtCore.QSize(105, 40))
        self.Reward.setMaximumSize(QtCore.QSize(105, 16777215))
        self.Reward.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.Reward.setAlignment(QtCore.Qt.AlignCenter)
        self.Reward.setObjectName("Reward")
        self.horizontalLayout_3.addWidget(self.Reward)
        self.StartLikes_R = QtWidgets.QPushButton(self.frame_12)
        self.StartLikes_R.setMinimumSize(QtCore.QSize(105, 40))
        self.StartLikes_R.setMaximumSize(QtCore.QSize(105, 16777215))
        self.StartLikes_R.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StartLikes_R.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.StartLikes_R.setObjectName("StartLikes_R")
        self.horizontalLayout_3.addWidget(self.StartLikes_R)
        self.StopLikes_R = QtWidgets.QPushButton(self.frame_12)
        self.StopLikes_R.setMinimumSize(QtCore.QSize(105, 40))
        self.StopLikes_R.setMaximumSize(QtCore.QSize(105, 16777215))
        self.StopLikes_R.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StopLikes_R.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.StopLikes_R.setObjectName("StopLikes_R")
        self.horizontalLayout_3.addWidget(self.StopLikes_R)
        self.ResultStartLikes_R = QtWidgets.QLabel(self.frame_12)
        self.ResultStartLikes_R.setMinimumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.ResultStartLikes_R.setFont(font)
        self.ResultStartLikes_R.setStyleSheet("QLabel {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"}")
        self.ResultStartLikes_R.setLineWidth(1)
        self.ResultStartLikes_R.setMidLineWidth(0)
        self.ResultStartLikes_R.setText("")
        self.ResultStartLikes_R.setScaledContents(False)
        self.ResultStartLikes_R.setAlignment(QtCore.Qt.AlignCenter)
        self.ResultStartLikes_R.setIndent(0)
        self.ResultStartLikes_R.setObjectName("ResultStartLikes_R")
        self.horizontalLayout_3.addWidget(self.ResultStartLikes_R, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.verticalLayout_21.addWidget(self.frame_12)
        self.verticalLayout_22.addWidget(self.frame_11, 0, QtCore.Qt.AlignTop)
        self.frame_15 = QtWidgets.QFrame(self.RepostPage)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 16777208))
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_5.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_22.addWidget(self.frame_15, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.verticalLayout_22.setStretch(2, 1)
        self.stackedWidget.addWidget(self.RepostPage)
        self.GroupFollowersPage = QtWidgets.QWidget()
        self.GroupFollowersPage.setObjectName("GroupFollowersPage")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.GroupFollowersPage)
        self.verticalLayout_28.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_28.setContentsMargins(0, 40, 0, 0)
        self.verticalLayout_28.setSpacing(0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.frame_19 = QtWidgets.QFrame(self.GroupFollowersPage)
        self.frame_19.setMinimumSize(QtCore.QSize(0, 100))
        self.frame_19.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_19.setStyleSheet("")
        self.frame_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_26.setContentsMargins(-1, 9, -1, 0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.frame_20 = QtWidgets.QFrame(self.frame_19)
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setSpacing(0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_5.setContentsMargins(10, 10, 10, 10)
        self.gridLayout_5.setSpacing(10)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.GroupFollowersSaveUrlButton = QtWidgets.QPushButton(self.frame_20)
        self.GroupFollowersSaveUrlButton.setMinimumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.GroupFollowersSaveUrlButton.setFont(font)
        self.GroupFollowersSaveUrlButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.GroupFollowersSaveUrlButton.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.GroupFollowersSaveUrlButton.setIcon(icon3)
        self.GroupFollowersSaveUrlButton.setCheckable(False)
        self.GroupFollowersSaveUrlButton.setObjectName("GroupFollowersSaveUrlButton")
        self.gridLayout_5.addWidget(self.GroupFollowersSaveUrlButton, 0, 1, 1, 1)
        self.GroupFollowersUrl = QtWidgets.QLineEdit(self.frame_20)
        self.GroupFollowersUrl.setMinimumSize(QtCore.QSize(0, 40))
        self.GroupFollowersUrl.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.GroupFollowersUrl.setObjectName("GroupFollowersUrl")
        self.gridLayout_5.addWidget(self.GroupFollowersUrl, 0, 0, 1, 1, QtCore.Qt.AlignTop)
        self.GroupFollowersResultSaveUrl = QtWidgets.QLabel(self.frame_20)
        self.GroupFollowersResultSaveUrl.setMinimumSize(QtCore.QSize(0, 30))
        self.GroupFollowersResultSaveUrl.setMaximumSize(QtCore.QSize(16777215, 50))
        self.GroupFollowersResultSaveUrl.setStyleSheet("border-radius: 2px;\n"
"padding: 10px;\n"
"")
        self.GroupFollowersResultSaveUrl.setText("")
        self.GroupFollowersResultSaveUrl.setObjectName("GroupFollowersResultSaveUrl")
        self.gridLayout_5.addWidget(self.GroupFollowersResultSaveUrl, 1, 1, 1, 1)
        self.gridLayout_5.setColumnStretch(0, 4)
        self.gridLayout_5.setColumnStretch(1, 1)
        self.gridLayout_5.setRowStretch(0, 2)
        self.verticalLayout_27.addLayout(self.gridLayout_5)
        self.verticalLayout_26.addWidget(self.frame_20)
        self.verticalLayout_28.addWidget(self.frame_19)
        self.frame_17 = QtWidgets.QFrame(self.GroupFollowersPage)
        self.frame_17.setEnabled(True)
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_25.setContentsMargins(10, 0, 11, 0)
        self.verticalLayout_25.setSpacing(0)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_18)
        self.horizontalLayout_7.setSpacing(7)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.GroupFollowersCount = QtWidgets.QLineEdit(self.frame_18)
        self.GroupFollowersCount.setEnabled(True)
        self.GroupFollowersCount.setMinimumSize(QtCore.QSize(105, 40))
        self.GroupFollowersCount.setMaximumSize(QtCore.QSize(105, 16777215))
        font = QtGui.QFont()
        font.setFamily("URW Gothic L")
        self.GroupFollowersCount.setFont(font)
        self.GroupFollowersCount.setToolTipDuration(-1)
        self.GroupFollowersCount.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.GroupFollowersCount.setText("")
        self.GroupFollowersCount.setCursorPosition(0)
        self.GroupFollowersCount.setAlignment(QtCore.Qt.AlignCenter)
        self.GroupFollowersCount.setObjectName("GroupFollowersCount")
        self.horizontalLayout_7.addWidget(self.GroupFollowersCount)
        self.GroupFollowersReward = QtWidgets.QLineEdit(self.frame_18)
        self.GroupFollowersReward.setMinimumSize(QtCore.QSize(0, 40))
        self.GroupFollowersReward.setMaximumSize(QtCore.QSize(105, 16777215))
        self.GroupFollowersReward.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.GroupFollowersReward.setAlignment(QtCore.Qt.AlignCenter)
        self.GroupFollowersReward.setObjectName("GroupFollowersReward")
        self.horizontalLayout_7.addWidget(self.GroupFollowersReward)
        self.GroupFollowersStart = QtWidgets.QPushButton(self.frame_18)
        self.GroupFollowersStart.setMinimumSize(QtCore.QSize(0, 40))
        self.GroupFollowersStart.setMaximumSize(QtCore.QSize(105, 16777215))
        self.GroupFollowersStart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.GroupFollowersStart.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.GroupFollowersStart.setObjectName("GroupFollowersStart")
        self.horizontalLayout_7.addWidget(self.GroupFollowersStart)
        self.GroupFollowersStop = QtWidgets.QPushButton(self.frame_18)
        self.GroupFollowersStop.setMinimumSize(QtCore.QSize(0, 40))
        self.GroupFollowersStop.setMaximumSize(QtCore.QSize(105, 16777215))
        self.GroupFollowersStop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.GroupFollowersStop.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.GroupFollowersStop.setObjectName("GroupFollowersStop")
        self.horizontalLayout_7.addWidget(self.GroupFollowersStop)
        self.GroupFollowersResultStart = QtWidgets.QLabel(self.frame_18)
        self.GroupFollowersResultStart.setMinimumSize(QtCore.QSize(140, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.GroupFollowersResultStart.setFont(font)
        self.GroupFollowersResultStart.setStyleSheet("QLabel {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"}")
        self.GroupFollowersResultStart.setLineWidth(1)
        self.GroupFollowersResultStart.setMidLineWidth(0)
        self.GroupFollowersResultStart.setText("")
        self.GroupFollowersResultStart.setScaledContents(False)
        self.GroupFollowersResultStart.setAlignment(QtCore.Qt.AlignCenter)
        self.GroupFollowersResultStart.setIndent(0)
        self.GroupFollowersResultStart.setObjectName("GroupFollowersResultStart")
        self.horizontalLayout_7.addWidget(self.GroupFollowersResultStart, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignVCenter)
        self.horizontalLayout_7.setStretch(0, 1)
        self.horizontalLayout_7.setStretch(1, 1)
        self.horizontalLayout_7.setStretch(2, 1)
        self.horizontalLayout_7.setStretch(3, 1)
        self.horizontalLayout_7.setStretch(4, 1)
        self.verticalLayout_25.addWidget(self.frame_18)
        self.verticalLayout_28.addWidget(self.frame_17)
        self.frame_21 = QtWidgets.QFrame(self.GroupFollowersPage)
        self.frame_21.setMaximumSize(QtCore.QSize(16777215, 16777208))
        self.frame_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_8.setContentsMargins(20, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_28.addWidget(self.frame_21)
        self.verticalLayout_28.setStretch(2, 1)
        self.stackedWidget.addWidget(self.GroupFollowersPage)
        self.FriendsPage = QtWidgets.QWidget()
        self.FriendsPage.setObjectName("FriendsPage")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.FriendsPage)
        self.verticalLayout_32.setContentsMargins(0, 40, 0, 0)
        self.verticalLayout_32.setSpacing(0)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.frame_25 = QtWidgets.QFrame(self.FriendsPage)
        self.frame_25.setEnabled(True)
        self.frame_25.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.frame_25)
        self.verticalLayout_31.setContentsMargins(10, 0, 11, 0)
        self.verticalLayout_31.setSpacing(0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.frame_26 = QtWidgets.QFrame(self.frame_25)
        self.frame_26.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_26)
        self.horizontalLayout_17.setSpacing(7)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.FriendsCount = QtWidgets.QLineEdit(self.frame_26)
        self.FriendsCount.setEnabled(True)
        self.FriendsCount.setMinimumSize(QtCore.QSize(120, 40))
        self.FriendsCount.setMaximumSize(QtCore.QSize(105, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.FriendsCount.setFont(font)
        self.FriendsCount.setToolTipDuration(-1)
        self.FriendsCount.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.FriendsCount.setText("")
        self.FriendsCount.setCursorPosition(0)
        self.FriendsCount.setAlignment(QtCore.Qt.AlignCenter)
        self.FriendsCount.setObjectName("FriendsCount")
        self.horizontalLayout_17.addWidget(self.FriendsCount)
        self.RewardFriends = QtWidgets.QLineEdit(self.frame_26)
        self.RewardFriends.setMinimumSize(QtCore.QSize(120, 40))
        self.RewardFriends.setMaximumSize(QtCore.QSize(105, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.RewardFriends.setFont(font)
        self.RewardFriends.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.RewardFriends.setAlignment(QtCore.Qt.AlignCenter)
        self.RewardFriends.setObjectName("RewardFriends")
        self.horizontalLayout_17.addWidget(self.RewardFriends)
        self.StartFriends = QtWidgets.QPushButton(self.frame_26)
        self.StartFriends.setMinimumSize(QtCore.QSize(105, 40))
        self.StartFriends.setMaximumSize(QtCore.QSize(105, 16777215))
        self.StartFriends.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StartFriends.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.StartFriends.setObjectName("StartFriends")
        self.horizontalLayout_17.addWidget(self.StartFriends)
        self.StopFriends = QtWidgets.QPushButton(self.frame_26)
        self.StopFriends.setMinimumSize(QtCore.QSize(105, 40))
        self.StopFriends.setMaximumSize(QtCore.QSize(105, 16777215))
        self.StopFriends.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.StopFriends.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.StopFriends.setObjectName("StopFriends")
        self.horizontalLayout_17.addWidget(self.StopFriends)
        self.ResultStartFriends = QtWidgets.QLabel(self.frame_26)
        self.ResultStartFriends.setMinimumSize(QtCore.QSize(130, 40))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.ResultStartFriends.setFont(font)
        self.ResultStartFriends.setStyleSheet("QLabel {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"}")
        self.ResultStartFriends.setLineWidth(1)
        self.ResultStartFriends.setMidLineWidth(0)
        self.ResultStartFriends.setText("")
        self.ResultStartFriends.setScaledContents(False)
        self.ResultStartFriends.setAlignment(QtCore.Qt.AlignCenter)
        self.ResultStartFriends.setIndent(0)
        self.ResultStartFriends.setObjectName("ResultStartFriends")
        self.horizontalLayout_17.addWidget(self.ResultStartFriends, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.verticalLayout_31.addWidget(self.frame_26)
        self.verticalLayout_32.addWidget(self.frame_25)
        self.frame_24 = QtWidgets.QFrame(self.FriendsPage)
        self.frame_24.setMaximumSize(QtCore.QSize(16777215, 16777208))
        self.frame_24.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Plain)
        self.frame_24.setObjectName("frame_24")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_24)
        self.verticalLayout_29.setContentsMargins(20, 0, 12, 300)
        self.verticalLayout_29.setSpacing(0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_24)
        self.comboBox_2.setMinimumSize(QtCore.QSize(120, 40))
        self.comboBox_2.setMaximumSize(QtCore.QSize(80, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setAutoFillBackground(False)
        self.comboBox_2.setStyleSheet("QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox_2.setMaxCount(3)
        self.comboBox_2.setIconSize(QtCore.QSize(16, 16))
        self.comboBox_2.setFrame(True)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout_29.addWidget(self.comboBox_2, 0, QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.verticalLayout_32.addWidget(self.frame_24)
        self.verticalLayout_32.setStretch(1, 1)
        self.stackedWidget.addWidget(self.FriendsPage)
        self.Settings = QtWidgets.QWidget()
        self.Settings.setObjectName("Settings")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Settings)
        self.verticalLayout_6.setSpacing(20)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame = QtWidgets.QFrame(self.Settings)
        self.frame.setStyleSheet("border-radius: 5px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_div_content_1 = QtWidgets.QFrame(self.frame)
        self.frame_div_content_1.setStyleSheet("background-color: rgb(41, 45, 56);\n"
"border-radius: 15px;\n"
"")
        self.frame_div_content_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_div_content_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_div_content_1.setObjectName("frame_div_content_1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.frame_div_content_1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame_title_wid_1 = QtWidgets.QFrame(self.frame_div_content_1)
        self.frame_title_wid_1.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_title_wid_1.setStyleSheet("background-color: rgb(39, 44, 54);")
        self.frame_title_wid_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title_wid_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title_wid_1.setObjectName("frame_title_wid_1")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_title_wid_1)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.labelBoxBlenderInstalation = QtWidgets.QLabel(self.frame_title_wid_1)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelBoxBlenderInstalation.setFont(font)
        self.labelBoxBlenderInstalation.setStyleSheet("")
        self.labelBoxBlenderInstalation.setObjectName("labelBoxBlenderInstalation")
        self.verticalLayout_8.addWidget(self.labelBoxBlenderInstalation)
        self.verticalLayout_7.addWidget(self.frame_title_wid_1)
        self.frame_9 = QtWidgets.QFrame(self.frame_div_content_1)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_11.setSpacing(10)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.UsernameDataSettings = QtWidgets.QLineEdit(self.frame_9)
        self.UsernameDataSettings.setMinimumSize(QtCore.QSize(400, 40))
        self.UsernameDataSettings.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.UsernameDataSettings.setInputMask("")
        self.UsernameDataSettings.setObjectName("UsernameDataSettings")
        self.verticalLayout_11.addWidget(self.UsernameDataSettings)
        self.PasswordDataSettings = QtWidgets.QLineEdit(self.frame_9)
        self.PasswordDataSettings.setMinimumSize(QtCore.QSize(0, 40))
        self.PasswordDataSettings.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.PasswordDataSettings.setInputMask("")
        self.PasswordDataSettings.setText("")
        self.PasswordDataSettings.setObjectName("PasswordDataSettings")
        self.verticalLayout_11.addWidget(self.PasswordDataSettings)
        self.TokenDataSettings = QtWidgets.QLineEdit(self.frame_9)
        self.TokenDataSettings.setMinimumSize(QtCore.QSize(0, 40))
        self.TokenDataSettings.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.TokenDataSettings.setInputMask("")
        self.TokenDataSettings.setObjectName("TokenDataSettings")
        self.verticalLayout_11.addWidget(self.TokenDataSettings)
        self.frame_clear = QtWidgets.QFrame(self.frame_9)
        self.frame_clear.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_clear.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_clear.setObjectName("frame_clear")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_clear)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.black_list_url = QtWidgets.QLineEdit(self.frame_clear)
        self.black_list_url.setMinimumSize(QtCore.QSize(0, 40))
        self.black_list_url.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.black_list_url.setObjectName("black_list_url")
        self.horizontalLayout_9.addWidget(self.black_list_url)
        self.comboBox = QtWidgets.QComboBox(self.frame_clear)
        self.comboBox.setMinimumSize(QtCore.QSize(150, 40))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.comboBox.setFont(font)
        self.comboBox.setAutoFillBackground(False)
        self.comboBox.setStyleSheet("QComboBox{\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding: 5px;\n"
"    padding-left: 10px;\n"
"}\n"
"QComboBox:hover{\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    color: rgb(85, 170, 255);    \n"
"    background-color: rgb(27, 29, 35);\n"
"    padding: 10px;\n"
"    selection-background-color: rgb(39, 44, 54);\n"
"}")
        self.comboBox.setMaxCount(3)
        self.comboBox.setIconSize(QtCore.QSize(16, 16))
        self.comboBox.setFrame(True)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_9.addWidget(self.comboBox)
        self.clear_black_list_button = QtWidgets.QPushButton(self.frame_clear)
        self.clear_black_list_button.setMinimumSize(QtCore.QSize(105, 40))
        self.clear_black_list_button.setMaximumSize(QtCore.QSize(105, 40))
        self.clear_black_list_button.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.clear_black_list_button.setObjectName("clear_black_list_button")
        self.horizontalLayout_9.addWidget(self.clear_black_list_button)
        self.verticalLayout_11.addWidget(self.frame_clear)
        self.verticalLayout_7.addWidget(self.frame_9)
        self.verticalLayout_15.addWidget(self.frame_div_content_1)
        self.verticalLayout_6.addWidget(self.frame)
        self.frame_3 = QtWidgets.QFrame(self.Settings)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_3.setStyleSheet("background-color: rgb(41, 45, 56);\n"
"border-radius: 15px;\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_24.setSpacing(0)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        self.frame_title_wid_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_title_wid_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.frame_title_wid_2.setStyleSheet("background-color: rgb(39, 44, 54);")
        self.frame_title_wid_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_title_wid_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_title_wid_2.setObjectName("frame_title_wid_2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_title_wid_2)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.labelBoxBlenderInstalation_2 = QtWidgets.QLabel(self.frame_title_wid_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.labelBoxBlenderInstalation_2.setFont(font)
        self.labelBoxBlenderInstalation_2.setStyleSheet("")
        self.labelBoxBlenderInstalation_2.setObjectName("labelBoxBlenderInstalation_2")
        self.verticalLayout_19.addWidget(self.labelBoxBlenderInstalation_2)
        self.verticalLayout_24.addWidget(self.frame_title_wid_2)
        self.frame_content_wid_1 = QtWidgets.QFrame(self.frame_3)
        self.frame_content_wid_1.setStyleSheet("background-color: rgb(41, 45, 56);\n"
"border-radius: 5px;\n"
"")
        self.frame_content_wid_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_content_wid_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_content_wid_1.setObjectName("frame_content_wid_1")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.frame_content_wid_1)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.frame_2 = QtWidgets.QFrame(self.frame_content_wid_1)
        self.frame_2.setMaximumSize(QtCore.QSize(280, 65))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.formLayout = QtWidgets.QFormLayout(self.frame_2)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.formLayout.setRowWrapPolicy(QtWidgets.QFormLayout.WrapLongRows)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setHorizontalSpacing(6)
        self.formLayout.setVerticalSpacing(0)
        self.formLayout.setObjectName("formLayout")
        self.getBalance = QtWidgets.QPushButton(self.frame_2)
        self.getBalance.setMinimumSize(QtCore.QSize(100, 40))
        self.getBalance.setMaximumSize(QtCore.QSize(100, 16777215))
        self.getBalance.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.getBalance.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.getBalance.setObjectName("getBalance")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.getBalance)
        self.LikesBalanceLabel = QtWidgets.QLabel(self.frame_2)
        self.LikesBalanceLabel.setMinimumSize(QtCore.QSize(100, 30))
        self.LikesBalanceLabel.setMaximumSize(QtCore.QSize(40, 40))
        self.LikesBalanceLabel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LikesBalanceLabel.setStyleSheet("QLabel {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"}\n"
"QLabel:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLabel:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.LikesBalanceLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.LikesBalanceLabel.setObjectName("LikesBalanceLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.LikesBalanceLabel)
        self.verticalLayout_23.addWidget(self.frame_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LabelCoupon = QtWidgets.QLineEdit(self.frame_content_wid_1)
        self.LabelCoupon.setMinimumSize(QtCore.QSize(0, 40))
        self.LabelCoupon.setMaximumSize(QtCore.QSize(205, 16777215))
        self.LabelCoupon.setStyleSheet("QLineEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(27, 29, 35);\n"
"    padding-left: 10px;\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}")
        self.LabelCoupon.setObjectName("LabelCoupon")
        self.horizontalLayout_2.addWidget(self.LabelCoupon)
        self.SaveCouponButton = QtWidgets.QPushButton(self.frame_content_wid_1)
        self.SaveCouponButton.setMinimumSize(QtCore.QSize(0, 40))
        self.SaveCouponButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.SaveCouponButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SaveCouponButton.setStyleSheet("QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;    \n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"QPushButton:pressed {    \n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}")
        self.SaveCouponButton.setObjectName("SaveCouponButton")
        self.horizontalLayout_2.addWidget(self.SaveCouponButton)
        self.ResultCoupon = QtWidgets.QLabel(self.frame_content_wid_1)
        self.ResultCoupon.setText("")
        self.ResultCoupon.setObjectName("ResultCoupon")
        self.horizontalLayout_2.addWidget(self.ResultCoupon)
        self.verticalLayout_23.addLayout(self.horizontalLayout_2)
        self.verticalLayout_24.addWidget(self.frame_content_wid_1)
        self.verticalLayout_6.addWidget(self.frame_3)
        self.verticalLayout_6.setStretch(0, 5)
        self.verticalLayout_6.setStretch(1, 5)
        self.stackedWidget.addWidget(self.Settings)
        self.verticalLayout_9.addWidget(self.stackedWidget)
        self.verticalLayout_5.addWidget(self.frame_content)
        self.frame_grip = QtWidgets.QFrame(self.frame_content_right)
        self.frame_grip.setMinimumSize(QtCore.QSize(0, 25))
        self.frame_grip.setMaximumSize(QtCore.QSize(16777215, 25))
        self.frame_grip.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.frame_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_grip.setObjectName("frame_grip")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_grip)
        self.horizontalLayout_22.setContentsMargins(0, 0, 2, 0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.frame_label_bottom = QtWidgets.QFrame(self.frame_grip)
        self.frame_label_bottom.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_label_bottom.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_label_bottom.setLineWidth(0)
        self.frame_label_bottom.setObjectName("frame_label_bottom")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_label_bottom)
        self.horizontalLayout_23.setContentsMargins(5, 0, 10, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.waslostUrl = QtWidgets.QPushButton(self.frame_label_bottom)
        self.waslostUrl.setMaximumSize(QtCore.QSize(16777215, 20))
        self.waslostUrl.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.waslostUrl.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.waslostUrl.setStyleSheet("border: 0;\n"
"text-align: left;\n"
"color: rgb(98, 103, 111);\n"
"\n"
"")
        self.waslostUrl.setIconSize(QtCore.QSize(0, 0))
        self.waslostUrl.setShortcut("")
        self.waslostUrl.setCheckable(False)
        self.waslostUrl.setAutoRepeatDelay(0)
        self.waslostUrl.setAutoRepeatInterval(0)
        self.waslostUrl.setObjectName("waslostUrl")
        self.horizontalLayout_23.addWidget(self.waslostUrl)
        self.label_version = QtWidgets.QLabel(self.frame_label_bottom)
        self.label_version.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.label_version.setFont(font)
        self.label_version.setStyleSheet("color: rgb(98, 103, 111);")
        self.label_version.setText("")
        self.label_version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_version.setObjectName("label_version")
        self.horizontalLayout_23.addWidget(self.label_version)
        self.horizontalLayout_22.addWidget(self.frame_label_bottom)
        self.frame_size_grip = QtWidgets.QFrame(self.frame_grip)
        self.frame_size_grip.setMaximumSize(QtCore.QSize(20, 20))
        self.frame_size_grip.setStyleSheet("QSizeGrip {\n"
"    background-image: url(icons/16x16/cil-size-grip.png);\n"
"    background-position: center;\n"
"    background-repeat: no-reperat;\n"
"}")
        self.frame_size_grip.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_size_grip.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_size_grip.setObjectName("frame_size_grip")
        self.horizontalLayout_22.addWidget(self.frame_size_grip)
        self.verticalLayout_5.addWidget(self.frame_grip)
        self.horizontalLayout_24.addWidget(self.frame_content_right)
        self.verticalLayout_2.addWidget(self.frame_center)
        self.horizontalLayout_11.addWidget(self.frame_main)
        MainWindow.setCentralWidget(self.centralwidget)
        self.action456 = QtWidgets.QAction(MainWindow)
        self.action456.setObjectName("action456")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_title_bar_top.setText(_translate("MainWindow", "Vk Stuff"))
        self.btn_minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.btn_maximize_restore.setToolTip(_translate("MainWindow", "Maximize"))
        self.btn_close.setToolTip(_translate("MainWindow", "Close"))
        self.label_top_info_2.setText(_translate("MainWindow", "| HOME"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Login"))
        self.lineEdit_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.checkBox.setText(_translate("MainWindow", "Login likest"))
        self.pushButton_4.setText(_translate("MainWindow", "Log in"))
        self.ResultOfLogin.setText(_translate("MainWindow", "Unsuccessful login"))
        self.SaveUrlButton.setText(_translate("MainWindow", "Save"))
        self.LabelLikesUrl.setPlaceholderText(_translate("MainWindow", "Url"))
        self.LikestCheckBox.setText(_translate("MainWindow", "Auto add likest task"))
        self.LikesCount.setPlaceholderText(_translate("MainWindow", "Likes Count"))
        self.StartLikes.setText(_translate("MainWindow", "Start"))
        self.StopLikes.setText(_translate("MainWindow", "Stop"))
        self.SaveUrlButton_R.setText(_translate("MainWindow", "Save"))
        self.LabelRepostsUrl.setPlaceholderText(_translate("MainWindow", "Repost URL"))
        self.RepostsCheckBox.setText(_translate("MainWindow", "Auto add likest task"))
        self.RepostsCount.setPlaceholderText(_translate("MainWindow", "Reposts Count"))
        self.Reward.setPlaceholderText(_translate("MainWindow", "Reward (min 4)"))
        self.StartLikes_R.setText(_translate("MainWindow", "Start"))
        self.StopLikes_R.setText(_translate("MainWindow", "Stop"))
        self.GroupFollowersSaveUrlButton.setText(_translate("MainWindow", "Save"))
        self.GroupFollowersUrl.setPlaceholderText(_translate("MainWindow", "Repost URL"))
        self.GroupFollowersCount.setPlaceholderText(_translate("MainWindow", "Followers Count"))
        self.GroupFollowersReward.setPlaceholderText(_translate("MainWindow", "Reward (min 2)"))
        self.GroupFollowersStart.setText(_translate("MainWindow", "Start"))
        self.GroupFollowersStop.setText(_translate("MainWindow", "Stop"))
        self.FriendsCount.setPlaceholderText(_translate("MainWindow", "Friends Count"))
        self.RewardFriends.setPlaceholderText(_translate("MainWindow", "Reward (min 2)"))
        self.StartFriends.setText(_translate("MainWindow", "Start"))
        self.StopFriends.setText(_translate("MainWindow", "Stop"))
        self.comboBox_2.setCurrentText(_translate("MainWindow", "Add friends"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Add friends"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Keep as followers"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Do nothing"))
        self.labelBoxBlenderInstalation.setText(_translate("MainWindow", "App Settings"))
        self.UsernameDataSettings.setPlaceholderText(_translate("MainWindow", "Username"))
        self.PasswordDataSettings.setPlaceholderText(_translate("MainWindow", "Password"))
        self.TokenDataSettings.setPlaceholderText(_translate("MainWindow", "Token"))
        self.black_list_url.setPlaceholderText(_translate("MainWindow", "Url"))
        self.comboBox.setCurrentText(_translate("MainWindow", "Main page"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Main page"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Public/Group"))
        self.clear_black_list_button.setText(_translate("MainWindow", "Clear Blacklist"))
        self.labelBoxBlenderInstalation_2.setText(_translate("MainWindow", "Likest"))
        self.getBalance.setText(_translate("MainWindow", "Get balance"))
        self.LikesBalanceLabel.setText(_translate("MainWindow", "0"))
        self.LabelCoupon.setPlaceholderText(_translate("MainWindow", "Coupon"))
        self.SaveCouponButton.setText(_translate("MainWindow", "Activate"))
        self.waslostUrl.setText(_translate("MainWindow", "Developed by @waslost"))
        self.action456.setText(_translate("MainWindow", "456"))
import files_rc
